# Server cluster addresses
# Add all server addresses in your cluster below

[[servers]]
address = "10.40.61.79:9000"

[[servers]]
address = "10.40.58.169:9000"

[[servers]]
address = "10.40.48.143:9000"
